### ISSUE TITLE
On board iGPU

### ISSUE THREAD

**Issue by kevinlin5115** [georgetree/hackintosh-10700k-Gigabyte-Z490-Vision-g#1]
Thank you very much for your post, 
I'm planning on buying this motherboard paired with a 10100 (using iGPU), 
Did you solve the problem for on board iGPU without a dGPU? 
Can't seem to find other information online regarding solving this issue.

**Comment by georgetree** [comment]
Yes!  iGPU(UHD 630) can work
Actually, i'm using Big sur without dGPU.

**Comment by kevinlin5115** [comment]
Thank you very much! 
Is it possible that I can use your efi with new SMBios despite that I have a different CPU? 
I'm building this machine for xcode for development hope it can work without issues.

**Comment by georgetree** [comment]
Not sure. You can try it.
