### ISSUE TITLE
Suggestion: Remove VRAM limitations + device-id for 10700k

### ISSUE THREAD

**Issue by augstb** [georgetree/hackintosh-10700k-Gigabyte-Z490-Vision-g#3]
Hello, thank you for your work on the framebuffer (I have the same hardware).

I have 2 suggestions :
- Remove these lines in your framebuffer patch :
```
<key>framebuffer-stolenmem</key>
<data>AAAwAQ==</data>
<key>framebuffer-fbmem</key>
<data>AACQAA==</data>
```
These lines are only useful when you can't set memory higher than 32MB. So remove these lines, and be sure to set `DVMT Pre-Allocated` memory to **64M**, and `DVMT Total Gfx Mem` to **MAX** in *BIOS > Settings > IO Ports*, because 4K resolution will not be accessible with only 32M.

- Change :
```
<key>device-id</key>
<data>mz4AAA==</data>
```
to
```
<key>device-id</key>
<data>xZsAAA==</data>
```
This is the correct device id for the 10700k (https://ark.intel.com/content/www/us/en/ark/products/199335/intel-core-i7-10700k-processor-16m-cache-up-to-5-10-ghz.html) 0x9BC5 -> 00 00 9B C5 -> **C59B0000**

This will probably don't change anything to your config because you are not using 4k dispays, but it can be useful for someone who passes by !
I hope that it will not break your configuration, as it is always very sensitive to changes...

**Comment by georgetree** [comment]
Thanks for your suggestion.
I will add link to readme

**Comment by imkhai** [comment]
I'm the guy looking for this. Thank you allot. I will try and let you guys know 😁

**Comment by augstb** [comment]
> I'm the guy looking for this. Thank you allot. I will try and let you guys know 😁

Excellent! Let me know if you also need to unplug and replug hdmi or DP cable at startup in order not to have graphical glitches 😊. If you don't, feel free to share your EFI directory 😁

**Comment by augstb** [comment]
> Let me know if you also need to unplug and replug hdmi or DP cable at startup in order not to have graphical glitches

**Little update :**
So you can set all ```framebuffer-conX-flags``` flags to ```<data>zwMAAA</data>``` (**_CF030000_**). This way unplug/replug HDMI or DP cable is not needed.
I just added flag ```CNConnectorAlwaysConnected``` to existing flags generated by @georgetree using Hackintool to generate flag string.

**Comment by azhinu** [comment]
Got Safari crashing while open YouTube, Reddit, Intel websites with this device-id
```
<key>device-id</key>
<data>xZsAAA==</data>
```


This section allows me to get 4k for two displays (without replug HDMI at boot) and Safari no crashing more:

```
			<dict>
			    <key>AAPL,ig-platform-id</key>
			    <data>BwCbPg==</data>
			    <key>device-id</key>
			    <data>mz4AAA==</data>
			    <key>framebuffer-con1-busid</key>
			    <data>BAAAAA==</data>
			    <key>framebuffer-con1-enable</key>
			    <data>AQAAAA==</data>
			    <key>framebuffer-con1-flags</key>
			    <data>zwMAAA==</data>
			    <key>framebuffer-con1-index</key>
			    <data>AwAAAA==</data>
			    <key>framebuffer-con1-pipe</key>
			    <data>CAAAAA==</data>
			    <key>framebuffer-con1-type</key>
			    <data>AAgAAA==</data>
			    <key>framebuffer-con2-busid</key>
			    <data>AQAAAA==</data>
			    <key>framebuffer-con2-enable</key>
			    <data>AQAAAA==</data>
			    <key>framebuffer-con2-index</key>
			    <data>AgAAAA==</data>
			    <key>framebuffer-con2-type</key>
			    <data>AAQAAA==</data>
			    <key>framebuffer-con2-flags</key>
			    <data>zwMAAA==</data>
			    <key>framebuffer-con2-pipe</key>
			    <data>CgAAAA==</data>
			    <key>framebuffer-con0-busid</key>
			    <data>BQAAAA==</data>
			    <key>framebuffer-con0-enable</key>
			    <data>AQAAAA==</data>
			    <key>framebuffer-con0-flags</key>
			    <data>zwMAAA==</data>
			    <key>framebuffer-con0-index</key>
			    <data>AQAAAA==</data>
			    <key>framebuffer-con0-pipe</key>
			    <data>CQAAAA==</data>
			    <key>framebuffer-con0-type</key>
			    <data>AAQAAA==</data>
			    <key>framebuffer-patch-enable</key>
			    <data>AQAAAA==</data>
			    <key>model</key>
			    <string>Intel UHD Graphics 630</string>
			</dict>
```

**Comment by augstb** [comment]
Nice ! It's good to see that this config gets reworked by some other folks sometimes ! Thank you very much for your contribution, I'll try this evening and give you feedback.

**Comment by augstb** [comment]
I tried it but can't get DRM working with that patch neither. I credited your contribution on my repo: [https://github.com/augstb/Hackintosh-Intel-i7-10700k-Gigabyte-Z490-Vision-G](https://github.com/augstb/Hackintosh-Intel-i7-10700k-Gigabyte-Z490-Vision-G). Hope that it will work for other people.
